### ISSUE TITLE
Missing cardinal-components-entity dependency

### ISSUE THREAD

**Issue by copygirl** [glisco03/victus#5] opened 2021-12-26 14:58 UTC
```
Unmet dependency listing:
	 - Mod 'Victus' (victus) 0.1.4+1.18 requires version 4.0.0 or later of cardinal-components-entity, which is missing!
```

From what I know, this is the kind of dependency that should be included in the mod as a jar-in-jar (if I remember the terminology correctly), right? I did try manually installing the Cardinal Components API but I don't think it's a mod that you can just do that with. May have to do with OnyxStudios/Cardinal-Components-API#105, and maybe it's fixed with release 4.0.1 but I'm not sure.

Either way it would be nice if this could be resolved as I'd love to have the mod in my pack.

**Comment by gliscowo** [comment] 2021-12-26 15:14
Yes, I would assume that the issue you linked is in fact the root cause here. I specifically didn't include CCA in Victus because it's such a common dependency to already have installed. I'll leave this open for now, but as a temporary fix you can either make a [Dependency Override](https://fabricmc.net/wiki/tutorial:dependency_overrides) to get Victus to launch anyways or directly download the [entity module](https://ladysnake.jfrog.io/artifactory/mods/io/github/onyxstudios/Cardinal-Components-API/cardinal-components-entity/4.0.1/cardinal-components-entity-4.0.1.jar) from their maven
Cheers

**Comment by copygirl** [comment] 2021-12-26 15:51
You say it's common to have it installed but out of my 156 mods installed so far (according to the main menu info), Victus is the only one that doesn't let my 1.18.1 instance load (same for 1.18 in the past). Grabbing the required jars from the Maven was a bit tedious but it works for now. Thank you!

**Comment by gliscowo** [comment] 2021-12-26 15:57
It is quite possible that Victus is the only mod that specifically declares dependencies for the indivdual modules, whereas most other mods depend on the entire thing, which is not technically the right thing to do. CCA is included in or required by (I don't quite remember) Trinkets API, which is the reason it is often pre-installed. Once 4.0.1 becomes public this issue should be resolved however, so I'll go ahead and close this for now.
Cheers

**Closed as completed** 2021-12-26 15:58 UTC
